const express = require('express');
const router = express.Router();
const UserController = require('../controllers/user_controller.js');
var key = "2e35f242a46d67eeb74aabc37d5e5d05";
router.post('/login/otp',UserController.loginotp);
router.get('/data/:login_method',UserController.logInMiddwre,UserController.dispData);
router.post('/signup/:login_method', UserController.signup);
//router.post('/signup/mobile', UserController.signupMobile);
router.post('/login/:login_method', UserController.login);
//router.post('/login/mobile', UserController.loginMobile);
router.post('/getotp', UserController.getotp);
router.get('/verify/:token/:user_varification_type', UserController.verify);
router.get('/reset/:token/:Password/:login_method',UserController.reset);
router.post('/forgotpassword/:login_method',UserController.forgotpassword);
router.put('/update/:login_method',UserController.logInMiddwre,UserController.update);
module.exports = router;